### ISSUE TITLE
Change Lemma to PoS

### ISSUE THREAD

**Issue by solodon4** [macdub/go-wiktionary-parse#3]
Great work! Just wanted to let you know what you call "Lemma" in DB is called "Part of Speech" or PoS for short. [Lemma](https://en.wikipedia.org/wiki/Lemma_(morphology)) is a normalized form of that word: e.g. worked -> work, were -> be etc.

**Comment by macdub** [comment]
@solodon4 I agree. There is a fair amount of clean up and organization that I need to do on this overall. There are code stuff that I'll update as well. These will be contained under the [lemma_lexical_cat](https://github.com/macdub/go-wiktionary-parse/tree/lemma_lexical_cat) branch.
